version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    depends_on:
      - db # Ensure the database starts before the frontend
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Change this to a strong password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306" # Expose the MySQL port
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
